### ISSUE TITLE
Fetch Timeout

### ISSUE THREAD

**Issue by Kesuaheli** [MinecraftPlayground/minecraft-manifest#3]
Sometimes, the action fails due to a timeout when trying to reach the version manifest from piston-meta.
Here's a failed run:
- ~~https:// github​​.com/schmanguage/resource-pack/actions/runs/11287319038/job/31393072089#step:2:1~~
- ~~https:// github.com/schmanguage/resource-pack/actions/runs/11391449530/job/31695270101#step:2:1~~
- https://github.com/schmanguage/resource-pack/actions/runs/11583257407/job/32248059585#step:2:1

**Comment by Mqxx** [comment]
Should be resolved!

**Comment by Kesuaheli** [comment]
@Mqxx still happening. It just failed (added new workflow link)

**Comment by Mqxx** [comment]
Ohh yea, sorry I forgot about that. I moved the Action from `Datapack-Registry/minecraft-manifest` to `MinecraftPlayground/minecraft-manifest`. Redirect should still work fine.

I never encountered that error, but it looks like the Mojang API does not respond. A potential solution could be to trigger the job not exactly `00:30` but rather than `00:30` or `01:00`. This also gets suggested by the Actions docs, because many users trigger their cron jobs at `00:00`.

**Comment by Mqxx** [comment]
Checkout this workflow: https://github.com/Resourcepack-Registry/data/actions/runs/11585605925/workflow#L4
All of them are using the `MinecraftPlayground/minecraft-manifest` and they are all passing.

**Comment by Kesuaheli** [comment]
> Redirect should still work fine.
Yeah, GH has no issue with that. As long as there exists no new repo with that old name, GH redirects any access to the new one.

> A potential solution could be to trigger the job not exactly `00:30`...
*`0:00` (;
> ...because many users trigger their cron jobs at `00:00`.
Ik, and I feel that. Usually, the workflow runs at `**:10`-`**:15`. But idc when exactly it runs or how consistent it runs.


I basically made a very simple program that just makes a HEAD request to check if the version manifest endpoint is available. Every 5 seconds.
Unfortunately, it is too simple... and because I'm stupid and can't program, the program ended itself as soon as it got no connection 🤦 Which happened two times.
One at `12:45`, and one at `17:20`. Both of them ran  for 2 hrs (±10 min) and exited with a "connection reset by peer" on a try to read tcp.

**Comment by Mqxx** [comment]
https://github.com/MinecraftPlayground/minecraft-manifest/issues/5
